### ISSUE TITLE
[ERROR] Compilation Error During Serve

### ISSUE THREAD

**Issue by fzerman** [GrapesJS/cli#245]
I took this compilation error during serve.  How can I fix this error?

```bash
Start the development server...

(node:4468) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createSnapshot' of undefined
    at C:\Users\Furkan\Desktop\template editor\node_modules\html-webpack-plugin\lib\webpack5\file-watcher-api.js:13:36
    at new Promise (<anonymous>)
    at Object.createSnapshot (C:\Users\Furkan\Desktop\template editor\node_modules\html-webpack-plugin\lib\webpack5\file-watcher-api.js:12:10)
    at C:\Users\Furkan\Desktop\template editor\node_modules\html-webpack-plugin\lib\cached-child-compiler.js:219:35
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:4468) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:4468) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
i ｢wds｣: Project is running at http://localhost:8081/
i ｢wds｣: webpack output is served from undefined
i ｢wds｣: Content not from webpack is served from C:\Users\Furkan\Desktop\template editor

Starting server on http://localhost:8081

C:\Users\Furkan\Desktop\template editor\node_modules\webpack\lib\Dependency.js:311
                throw new Error(
                ^

Error: module property was removed from Dependency (use compilation.moduleGraph.updateModule(dependency, module) instead)
    at ProvidedDependency.set (C:\Users\Furkan\Desktop\template editor\node_modules\webpack\lib\Dependency.js:311:9)
    at iterationDependencies (C:\Users\Furkan\Desktop\template editor\node_modules\grapesjs-cli\node_modules\webpack\lib\Compilation.js:940:21)
    at C:\Users\Furkan\Desktop\template editor\node_modules\grapesjs-cli\node_modules\webpack\lib\Compilation.js:950:8
    at C:\Users\Furkan\Desktop\template editor\node_modules\grapesjs-cli\node_modules\webpack\lib\NormalModuleFactory.js:409:6
    at C:\Users\Furkan\Desktop\template editor\node_modules\grapesjs-cli\node_modules\webpack\lib\NormalModuleFactory.js:155:13
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (C:\Users\Furkan\Desktop\template editor\node_modules\grapesjs-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at C:\Users\Furkan\Desktop\template editor\node_modules\grapesjs-cli\node_modules\webpack\lib\NormalModuleFactory.js:138:29
    at C:\Users\Furkan\Desktop\template editor\node_modules\grapesjs-cli\node_modules\webpack\lib\NormalModuleFactory.js:346:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by artf** [comment]
I'm not sure but, by looking at `html-webpack-plugin\lib\webpack5` seems like your `html-webpack-plugin` is trying to load webpack v5, where now grapesjs-cli is still using v4
